Repository vapor/http, pull requests merged in 2018-08, with the labels that each got.

#299 Fix for HTTPDecoder NIO issue
  Sources/HTTP/Responder/HTTPClientProtocolUpgrader.swift
Labels: bug

#300 Add connectTimeout support to HTTPClient
  Sources/HTTP/Responder/HTTPClient.swift
Labels: enhancement

#302 3.1.0 release
  Package.swift
  Sources/HTTP/Cookies/HTTPCookies.swift
  Sources/HTTP/Responder/HTTPServer.swift
  Sources/HTTP/Utilities/HTTPHeaders+Basic.swift
  Sources/HTTP/Utilities/HTTPHeaders+Bearer.swift
  Sources/HTTP/Utilities/RFC1123.swift
  Sources/HTTPPerformance/main.swift
  Tests/HTTPTests/HTTPClientTests.swift
  Tests/HTTPTests/HTTPTests.swift
Labels: bug, enhancement

#304 don't send bodies for 204 (no content) responses
  Sources/HTTP/Responder/HTTPServer.swift
Labels: enhancement

#306 Send close header if the request 'keep alive' is false
  Sources/HTTP/Responder/HTTPServer.swift
Labels: bug, enhancement
